# Generated by Django 3.2.9 on 2022-05-11 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('shortcut', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('rso_alarm', models.TextField(blank=True, null=True)),
                ('rso_icon', models.TextField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('repetition', models.BooleanField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('water_level_value', models.IntegerField(blank=True, null=True)),
                ('water_level_warning_status_value', models.IntegerField(blank=True, null=True)),
                ('water_level_alarm_status_value', models.IntegerField(blank=True, null=True)),
                ('water_level_trend', models.IntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, max_length=64, null=True)),
                ('river_name', models.TextField(blank=True, null=True)),
                ('location_name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('province_city', models.CharField(blank=True, max_length=128, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('province_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.province')),
            ],
        ),
    ]
