# Generated by Django 3.2.9 on 2022-05-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='provinces',
            field=models.ManyToManyField(blank=True, related_name='user_list', to='news.Province'),
        ),
    ]
